-- Snowflake environment setup
-- Warehouse, database and schemas were created during project setup.

CREATE WAREHOUSE BANK_DA_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE BANK_ANALYTICS;

CREATE SCHEMA BANK_ANALYTICS.RAW_DATA;
CREATE SCHEMA BANK_ANALYTICS.ANALYTICS;

USE WAREHOUSE BANK_DA_WH;
USE DATABASE BANK_ANALYTICS;
USE SCHEMA RAW_DATA;

-- Source table is loaded into:
-- RAW_DATA.FINANCIAL_LOAN_DATA

-- Cleaned analytical table:
-- ANALYTICS.FINANCIAL_LOAN_CLEANED
