-- Loan Risk & Profitability Analytics
-- Data quality profiling and validation

-- Table structure
DESC TABLE RAW_DATA.FINANCIAL_LOAN_DATA;

-- ID validation
SELECT ID
FROM ANALYTICS.FINANCIAL_LOAN_CLEANED
WHERE ID IS NULL;

SELECT ID, COUNT(*)
FROM ANALYTICS.FINANCIAL_LOAN_CLEANED
GROUP BY ID
HAVING COUNT(*) > 1;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(ID) AS NON_NULL_IDS,
    COUNT(DISTINCT ID) AS UNIQUE_IDS
FROM RAW_DATA.FINANCIAL_LOAN_DATA;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ID) AS UNIQUE_IDS,
    COUNT(*) - COUNT(DISTINCT ID) AS DUPLICATE_ID_ROWS,
    COUNT_IF(ID IS NULL) AS NULL_ID_ROWS
FROM RAW_DATA.FINANCIAL_LOAN_DATA;

-- NULL checks
SELECT
    COUNT_IF(ADDRESS_STATE IS NULL) AS ADDRESS_STATE_NULLS,
    COUNT_IF(APPLICATION_TYPE IS NULL) AS APPLICATION_TYPE_NULLS,
    COUNT_IF(EMP_LENGTH IS NULL) AS EMP_LENGTH_NULLS,
    COUNT_IF(EMP_TITLE IS NULL) AS EMP_TITLE_NULLS,
    COUNT_IF(GRADE IS NULL) AS GRADE_NULLS,
    COUNT_IF(HOME_OWNERSHIP IS NULL) AS HOME_OWNERSHIP_NULLS,
    COUNT_IF(ISSUE_DATE IS NULL) AS ISSUE_DATE_NULLS,
    COUNT_IF(LAST_CREDIT_PULL_DATE IS NULL) AS LAST_CREDIT_PULL_DATE_NULLS,
    COUNT_IF(LAST_PAYMENT_DATE IS NULL) AS LAST_PAYMENT_DATE_NULLS,
    COUNT_IF(LOAN_STATUS IS NULL) AS LOAN_STATUS_NULLS,
    COUNT_IF(NEXT_PAYMENT_DATE IS NULL) AS NEXT_PAYMENT_DATE_NULLS,
    COUNT_IF(MEMBER_ID IS NULL) AS MEMBER_ID_NULLS,
    COUNT_IF(PURPOSE IS NULL) AS PURPOSE_NULLS,
    COUNT_IF(SUB_GRADE IS NULL) AS SUB_GRADE_NULLS,
    COUNT_IF(TERM IS NULL) AS TERM_NULLS,
    COUNT_IF(VERIFICATION_STATUS IS NULL) AS VERIFICATION_STATUS_NULLS,
    COUNT_IF(ANNUAL_INCOME IS NULL) AS ANNUAL_INCOME_NULLS,
    COUNT_IF(DTI IS NULL) AS DTI_NULLS,
    COUNT_IF(INSTALLMENT IS NULL) AS INSTALLMENT_NULLS,
    COUNT_IF(INT_RATE IS NULL) AS INT_RATE_NULLS,
    COUNT_IF(LOAN_AMOUNT IS NULL) AS LOAN_AMOUNT_NULLS,
    COUNT_IF(TOTAL_ACC IS NULL) AS TOTAL_ACC_NULLS,
    COUNT_IF(TOTAL_PAYMENT IS NULL) AS TOTAL_PAYMENT_NULLS
FROM RAW_DATA.FINANCIAL_LOAN_DATA;

-- Blank text checks
SELECT
    COUNT_IF(TRIM(ADDRESS_STATE) = '') AS ADDRESS_STATE_BLANKS,
    COUNT_IF(TRIM(APPLICATION_TYPE) = '') AS APPLICATION_TYPE_BLANKS,
    COUNT_IF(TRIM(EMP_LENGTH) = '') AS EMP_LENGTH_BLANKS,
    COUNT_IF(TRIM(EMP_TITLE) = '') AS EMP_TITLE_BLANKS,
    COUNT_IF(TRIM(GRADE) = '') AS GRADE_BLANKS,
    COUNT_IF(TRIM(HOME_OWNERSHIP) = '') AS HOME_OWNERSHIP_BLANKS,
    COUNT_IF(TRIM(ISSUE_DATE) = '') AS ISSUE_DATE_BLANKS,
    COUNT_IF(TRIM(LOAN_STATUS) = '') AS LOAN_STATUS_BLANKS,
    COUNT_IF(TRIM(PURPOSE) = '') AS PURPOSE_BLANKS,
    COUNT_IF(TRIM(SUB_GRADE) = '') AS SUB_GRADE_BLANKS,
    COUNT_IF(TRIM(TERM) = '') AS TERM_BLANKS,
    COUNT_IF(TRIM(VERIFICATION_STATUS) = '') AS VERIFICATION_STATUS_BLANKS
FROM RAW_DATA.FINANCIAL_LOAN_DATA;

-- Category profiling
SELECT HOME_OWNERSHIP, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY HOME_OWNERSHIP
ORDER BY HOME_OWNERSHIP;

SELECT PURPOSE, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY PURPOSE
ORDER BY PURPOSE;

SELECT GRADE, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY GRADE
ORDER BY GRADE;

SELECT SUB_GRADE, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY SUB_GRADE
ORDER BY SUB_GRADE;

SELECT LOAN_STATUS, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY LOAN_STATUS
ORDER BY LOAN_STATUS;

SELECT VERIFICATION_STATUS, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY VERIFICATION_STATUS
ORDER BY VERIFICATION_STATUS;

SELECT ADDRESS_STATE, COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY ADDRESS_STATE
ORDER BY ADDRESS_STATE;

-- Text consistency checks
SELECT ID, EMP_TITLE, TRIM(EMP_TITLE) AS CLEANED_EMP_TITLE
FROM RAW_DATA.FINANCIAL_LOAN_DATA
WHERE EMP_TITLE IS NOT NULL
  AND EMP_TITLE <> TRIM(EMP_TITLE)
LIMIT 100;

SELECT
    UPPER(TRIM(PURPOSE)) AS NORMALIZED_PURPOSE,
    COUNT(DISTINCT PURPOSE) AS ORIGINAL_VARIATIONS,
    COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY UPPER(TRIM(PURPOSE))
HAVING COUNT(DISTINCT PURPOSE) > 1
ORDER BY RECORD_COUNT DESC;

SELECT ID, HOME_OWNERSHIP, TRIM(HOME_OWNERSHIP) AS CLEANED_HOME_OWNERSHIP
FROM RAW_DATA.FINANCIAL_LOAN_DATA
WHERE HOME_OWNERSHIP IS NOT NULL
  AND HOME_OWNERSHIP <> TRIM(HOME_OWNERSHIP)
LIMIT 100;

SELECT ID, PURPOSE, TRIM(PURPOSE) AS CLEANED_PURPOSE
FROM RAW_DATA.FINANCIAL_LOAN_DATA
WHERE PURPOSE IS NOT NULL
  AND PURPOSE <> TRIM(PURPOSE)
LIMIT 100;

SELECT
    UPPER(TRIM(HOME_OWNERSHIP)) AS NORMALIZED_HOME_OWNERSHIP,
    COUNT(DISTINCT HOME_OWNERSHIP) AS ORIGINAL_VARIATIONS,
    COUNT(*) AS RECORD_COUNT
FROM RAW_DATA.FINANCIAL_LOAN_DATA
GROUP BY UPPER(TRIM(HOME_OWNERSHIP))
HAVING COUNT(DISTINCT HOME_OWNERSHIP) > 1
ORDER BY RECORD_COUNT DESC;

-- Numeric profiling
SELECT
    MIN(ANNUAL_INCOME) AS MIN_INCOME,
    MAX(ANNUAL_INCOME) AS MAX_INCOME,
    AVG(ANNUAL_INCOME) AS AVG_INCOME,
    MIN(DTI) AS MIN_DTI,
    MAX(DTI) AS MAX_DTI,
    MIN(INT_RATE) AS MIN_INT_RATE,
    MAX(INT_RATE) AS MAX_INT_RATE,
    MIN(LOAN_AMOUNT) AS MIN_LOAN_AMOUNT,
    MAX(LOAN_AMOUNT) AS MAX_LOAN_AMOUNT,
    MIN(INSTALLMENT) AS MIN_INSTALLMENT,
    MAX(INSTALLMENT) AS MAX_INSTALLMENT,
    MIN(TOTAL_PAYMENT) AS MIN_TOTAL_PAYMENT,
    MAX(TOTAL_PAYMENT) AS MAX_TOTAL_PAYMENT
FROM RAW_DATA.FINANCIAL_LOAN_DATA;

-- Negative-value checks
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE LOAN_AMOUNT < 0;
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE ANNUAL_INCOME < 0;
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE INT_RATE < 0;
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE INSTALLMENT < 0;
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE DTI < 0;
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE TOTAL_PAYMENT < 0;
SELECT * FROM RAW_DATA.FINANCIAL_LOAN_DATA WHERE TOTAL_ACC < 0;

SELECT DISTINCT TERM
FROM RAW_DATA.FINANCIAL_LOAN_DATA
ORDER BY TERM;
