-- Loan Risk & Profitability Analytics
-- Scheduled incremental cleaning and loading

-- Primary key added to the cleaned table after confirming
-- that ID is non-null and unique.
ALTER TABLE ANALYTICS.FINANCIAL_LOAN_CLEANED
ADD CONSTRAINT PK_FINANCIAL_LOAN PRIMARY KEY (ID);

CREATE OR REPLACE TASK ANALYTICS.FINANCIAL_LOAN_TASK
    WAREHOUSE = BANK_DA_WH
    SCHEDULE = '15 minutes'
    WHEN SYSTEM$STREAM_HAS_DATA('RAW_DATA.FINANCIAL_LOAN_STREAM')
AS
MERGE INTO ANALYTICS.FINANCIAL_LOAN_CLEANED AS TARGET
USING (
    SELECT
        ID,
        NULLIF(TRIM(ADDRESS_STATE), '') AS ADDRESS_STATE,
        NULLIF(TRIM(APPLICATION_TYPE), '') AS APPLICATION_TYPE,
        NULLIF(TRIM(EMP_LENGTH), '') AS EMP_LENGTH,
        COALESCE(
            NULLIF(TRIM(EMP_TITLE), ''),
            'Unknown'
        ) AS EMP_TITLE,
        NULLIF(TRIM(GRADE), '') AS GRADE,
        NULLIF(TRIM(HOME_OWNERSHIP), '') AS HOME_OWNERSHIP,
        NULLIF(TRIM(ISSUE_DATE), '') AS ISSUE_DATE,
        NULLIF(TRIM(LAST_CREDIT_PULL_DATE), '') AS LAST_CREDIT_PULL_DATE,
        NULLIF(TRIM(LAST_PAYMENT_DATE), '') AS LAST_PAYMENT_DATE,
        NULLIF(TRIM(LOAN_STATUS), '') AS LOAN_STATUS,
        NULLIF(TRIM(NEXT_PAYMENT_DATE), '') AS NEXT_PAYMENT_DATE,
        MEMBER_ID,
        NULLIF(TRIM(PURPOSE), '') AS PURPOSE,
        NULLIF(TRIM(SUB_GRADE), '') AS SUB_GRADE,
        NULLIF(TRIM(TERM), '') AS TERM,
        NULLIF(TRIM(VERIFICATION_STATUS), '') AS VERIFICATION_STATUS,
        ANNUAL_INCOME,
        DTI,
        INSTALLMENT,
        INT_RATE,
        LOAN_AMOUNT,
        TOTAL_ACC,
        TOTAL_PAYMENT
    FROM RAW_DATA.FINANCIAL_LOAN_STREAM
    WHERE METADATA$ACTION = 'INSERT'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ID
        ORDER BY METADATA$ROW_ID
    ) = 1
) AS SOURCE
ON TARGET.ID = SOURCE.ID

WHEN MATCHED THEN UPDATE SET
    ADDRESS_STATE = SOURCE.ADDRESS_STATE,
    APPLICATION_TYPE = SOURCE.APPLICATION_TYPE,
    EMP_LENGTH = SOURCE.EMP_LENGTH,
    EMP_TITLE = SOURCE.EMP_TITLE,
    GRADE = SOURCE.GRADE,
    HOME_OWNERSHIP = SOURCE.HOME_OWNERSHIP,
    ISSUE_DATE = SOURCE.ISSUE_DATE,
    LAST_CREDIT_PULL_DATE = SOURCE.LAST_CREDIT_PULL_DATE,
    LAST_PAYMENT_DATE = SOURCE.LAST_PAYMENT_DATE,
    LOAN_STATUS = SOURCE.LOAN_STATUS,
    NEXT_PAYMENT_DATE = SOURCE.NEXT_PAYMENT_DATE,
    MEMBER_ID = SOURCE.MEMBER_ID,
    PURPOSE = SOURCE.PURPOSE,
    SUB_GRADE = SOURCE.SUB_GRADE,
    TERM = SOURCE.TERM,
    VERIFICATION_STATUS = SOURCE.VERIFICATION_STATUS,
    ANNUAL_INCOME = SOURCE.ANNUAL_INCOME,
    DTI = SOURCE.DTI,
    INSTALLMENT = SOURCE.INSTALLMENT,
    INT_RATE = SOURCE.INT_RATE,
    LOAN_AMOUNT = SOURCE.LOAN_AMOUNT,
    TOTAL_ACC = SOURCE.TOTAL_ACC,
    TOTAL_PAYMENT = SOURCE.TOTAL_PAYMENT

WHEN NOT MATCHED THEN INSERT (
    ID,
    ADDRESS_STATE,
    APPLICATION_TYPE,
    EMP_LENGTH,
    EMP_TITLE,
    GRADE,
    HOME_OWNERSHIP,
    ISSUE_DATE,
    LAST_CREDIT_PULL_DATE,
    LAST_PAYMENT_DATE,
    LOAN_STATUS,
    NEXT_PAYMENT_DATE,
    MEMBER_ID,
    PURPOSE,
    SUB_GRADE,
    TERM,
    VERIFICATION_STATUS,
    ANNUAL_INCOME,
    DTI,
    INSTALLMENT,
    INT_RATE,
    LOAN_AMOUNT,
    TOTAL_ACC,
    TOTAL_PAYMENT
)
VALUES (
    SOURCE.ID,
    SOURCE.ADDRESS_STATE,
    SOURCE.APPLICATION_TYPE,
    SOURCE.EMP_LENGTH,
    SOURCE.EMP_TITLE,
    SOURCE.GRADE,
    SOURCE.HOME_OWNERSHIP,
    SOURCE.ISSUE_DATE,
    SOURCE.LAST_CREDIT_PULL_DATE,
    SOURCE.LAST_PAYMENT_DATE,
    SOURCE.LOAN_STATUS,
    SOURCE.NEXT_PAYMENT_DATE,
    SOURCE.MEMBER_ID,
    SOURCE.PURPOSE,
    SOURCE.SUB_GRADE,
    SOURCE.TERM,
    SOURCE.VERIFICATION_STATUS,
    SOURCE.ANNUAL_INCOME,
    SOURCE.DTI,
    SOURCE.INSTALLMENT,
    SOURCE.INT_RATE,
    SOURCE.LOAN_AMOUNT,
    SOURCE.TOTAL_ACC,
    SOURCE.TOTAL_PAYMENT
);

-- Task administration
SHOW TASKS;

-- Resume after creation/replacement
ALTER TASK ANALYTICS.FINANCIAL_LOAN_TASK RESUME;

-- Optional manual execution for testing
-- EXECUTE TASK ANALYTICS.FINANCIAL_LOAN_TASK;

-- Task history
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'FINANCIAL_LOAN_TASK'
ORDER BY SCHEDULED_TIME DESC
LIMIT 5;
